name: codes3d
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - biopython #=1.77
    - numpy=1.19.1
    - pandas=1.0.5
    - pandas-plink #=2.0.4
    - psycopg2 #=2.8.5
    - pybedtools #=0.8.1
    - requests #=2.24.0
    - scikits-bootstrap #=1.0.1
    - SQLAlchemy #=1.3.18
    - SQLAlchemy-Utils #=0.36.8
    - statsmodels #=0.11.1
    - pytorch #=1.9.0
    - tqdm #=4.48.0
    
